### ISSUE TITLE
rms not defined

### ISSUE THREAD

**Issue by purkun01** [ReactionMechanismGenerator/T3#107]
After doing the installation when I am trying to run the RMG superminimal example it is showing error like rms not defined.
exerpt of the error is as follows:-

Loading transport library from NIST_Fluorine.py in /home/purbadree/RMG/RMG-database/input/transport/libraries...
Loading transport library from GRI-Mech.py in /home/purbadree/RMG/RMG-database/input/transport/libraries...
Loading transport library from NOx2018.py in /home/purbadree/RMG/RMG-database/input/transport/libraries...
Loading transport library from PrimaryTransportLibrary.py in /home/purbadree/RMG/RMG-database/input/transport/libraries...
Loading transport library from OneDMinN2.py in /home/purbadree/RMG/RMG-database/input/transport/libraries...
Loading transport group database from /home/purbadree/RMG/RMG-database/input/transport/groups...
Loading frequencies group database from /home/purbadree/RMG/RMG-database/input/statmech/groups...
Loading solvation thermodynamics group database from /home/purbadree/RMG/RMG-database/input/solvation/groups...
Loading thermodynamics library from primaryThermoLibrary.py in /home/purbadree/RMG/RMG-database/input/thermo/libraries...
Loading thermodynamics group database from /home/purbadree/RMG/RMG-database/input/thermo/groups...
Adding rate rules from training set in kinetics families...
Filling in rate rules in kinetics families by averaging...
Traceback (most recent call last):
  File "rmg.py", line 118, in <module>
    main()
  File "rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/purbadree/RMG/RMG-Py/rmgpy/rmg/main.py", line 717, in execute
    self.initialize(**kwargs)
  File "/home/purbadree/RMG/RMG-Py/rmgpy/rmg/main.py", line 522, in initialize
    self.reaction_model.add_species_to_edge(spec)
  File "/home/purbadree/RMG/RMG-Py/rmgpy/rmg/model.py", line 1184, in add_species_to_edge
    self.edge.phase_system.phases["Default"].add_species(spec)
  File "/home/purbadree/RMG/RMG-Py/rmgpy/rmg/reactors.py", line 288, in add_species
    spec = to_rms(spc)
  File "/home/purbadree/RMG/RMG-Py/rmgpy/rmg/reactors.py", line 587, in to_rms
    rad = rms.getspeciesradius(atomnums, bondnum)
NameError: name 'rms' is not defined

**Comment by purkun01** [comment]
Followed the instructions as said in the http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html and the model is working.

Please do not refer the RMG 2021 lecture 2 else you will get the same error as shown above. Also no need to create 2 environments as given in RMG 2021 lecture 2.
